// Generated by scripts/models/build.mjs — edit sources.json and re-run, not this file.
//
// The GLBs are imported with `?url` rather than read from a public/ directory, for the reason #6
// learned the hard way with MapLibre's worker: a URL Vite can see is a URL that survives the
// production build. These imports make the bundler fingerprint each model and hand back the final
// path, in dev and on Vercel alike.

import boat_speedUrl from './boat-speed.glb?url'
import ferryUrl from './ferry.glb?url'
import train_sleeper_noseUrl from './train-sleeper-nose.glb?url'
import train_sleeper_middleUrl from './train-sleeper-middle.glb?url'
import train_sleeper_tailUrl from './train-sleeper-tail.glb?url'
import train_intercity_noseUrl from './train-intercity-nose.glb?url'
import train_intercity_middleUrl from './train-intercity-middle.glb?url'
import train_intercity_tailUrl from './train-intercity-tail.glb?url'
import vanUrl from './van.glb?url'
import stay_hotelUrl from './stay-hotel.glb?url'
import airlinerUrl from './airliner.glb?url'

import { MODEL_ASSETS, type ModelAssetKey } from './model-assets'

export * from './model-assets'

export const MODEL_URLS: Record<ModelAssetKey, string> = {
  boat_speed: boat_speedUrl,
  ferry: ferryUrl,
  train_sleeper_nose: train_sleeper_noseUrl,
  train_sleeper_middle: train_sleeper_middleUrl,
  train_sleeper_tail: train_sleeper_tailUrl,
  train_intercity_nose: train_intercity_noseUrl,
  train_intercity_middle: train_intercity_middleUrl,
  train_intercity_tail: train_intercity_tailUrl,
  van: vanUrl,
  stay_hotel: stay_hotelUrl,
  airliner: airlinerUrl,
}

/** The URL to fetch a model from, keyed the same way as the table. */
export const modelUrl = (key: ModelAssetKey): string => MODEL_URLS[key]

export const modelAsset = (key: ModelAssetKey) => MODEL_ASSETS[key]
