// Generated by scripts/models/build.mjs — edit sources.json and re-run, not this file.
//
// Every number here was measured from the shipped GLB. Source units are incoherent across the four
// kits and even inside one of them (a suburban house is 0.74 units tall; a van is 2.75 units long),
// so nothing may be scaled 1:1 and no per-kit constant would do.
//
// The model matrix maps one unit to one metre (src/map/model-matrix.ts), so:
//
//   metres = source units × scale
//
// Scale is solved on **height** for every Kenney asset, and that is the load-bearing decision here.
// Kenney's vehicles are faithful in cross-section and compressed in length — a double-deck carriage
// is 2.5 units long on a 1.92-unit body, where a real one is 26 m long on a 3 m body. Solving for a
// true 26 m length gives a carriage 20 m TALL, towering over an 8 m guesthouse and wrecking the
// one-world read; solving for a true height leaves each piece stubby, which is the toy register the
// Diorama already committed to. Train length comes from coupling the a/b/c segments, which is what
// they are for. The airliner is the exception and is solved on wingspan.
//
// `readsAtM` / `readsAtAxis` record which size was solved for. A Vehicle crossing a continent will
// want exaggerating well past life size to stay visible — multiply there (#8), and leave this table
// stating the truth.
//
// What the files already are, measured from the shipped GLBs rather than assumed — all of it matters
// to whoever draws them:
//
// Every material is doubleSided already, so the mirrored mercator frame cannot cull half a
// model away — the trap proof-triangle.ts guards against with side: DoubleSide.
// Every material is metallicFactor 0 — matte on arrival, no specular to fight, which is the
// Diorama register #11 will build on.
// 10 of 11 materials carry a baseColorTexture, all of them the kit atlas now
// embedded in the GLB. The airliner is the untextured one, so its colour lives in the material
// and #11 can set it outright. A loader must mark the atlas as sRGB.
// These are PBR metallic-roughness materials, so they need a light in the scene. The scaffold's
// proof triangle uses MeshBasicMaterial and adds none — whoever draws the first model adds the
// lighting with it (#7).

export type ModelRole = 'vehicle' | 'stay'

export type ModelAsset = {
  id: string
  /** Filename inside this directory. The URL comes from index.ts, which lets Vite fingerprint it. */
  file: string
  /** The Mode this Vehicle depicts. Absent on a Stay Marker. */
  mode?: string
  role: ModelRole
  /** Metres per source unit. */
  scale: number
  /** Metres to lift the model so it stands on the ground rather than sinking into it. */
  yOffset: number
  /**
   * Radians about Y to bring the model's nose onto +Z. Zero for every asset in the set today —
   * verified by eye, not assumed — and kept because the next asset may need it.
   */
  yaw: number
  /** The real-world size `scale` was solved for. */
  readsAtM: number
  /** The axis `readsAtM` was measured on: height for the Kenney set, wingspan for the airliner. */
  readsAtAxis: 'x' | 'y' | 'z'
  /**
   * The model's real size once scaled, as [x, y, z] metres — width, height, length.
   *
   * Here because #8 needs it: a train is drawn by coupling the a/b/c segments, and the length of each
   * is the spacing between them. Deriving it from a GLB at runtime would mean parsing accessor bounds
   * in the browser to recover a number already measured at build time.
   */
  sizeM: readonly [x: number, y: number, z: number]
  licence: string
  author: string
  source: string
}

export const MODEL_ASSETS = {
  /**
   * A small open longtail-ish boat: the island-hop register. Reads at ~4.9 m long.
   *
   * Solved on Y at 2.2 m, which puts it at 4.94 m long, 2.62 m wide, 2.2 m tall.
   * 156 tris · 24.4 kB · source box 1.785 × 1.5 × 3.37 units.
   */
  boat_speed: {
    id: 'boat-speed',
    file: 'boat-speed.glb',
    mode: 'boat',
    role: 'vehicle',
    scale: 1.466667,
    yOffset: 0,
    yaw: 0,
    readsAtM: 2.2,
    readsAtAxis: 'y',
    sizeM: [2.62, 2.2, 4.94],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/watercraft-kit',
  },
  /**
   * Funnelled passenger liner, near fore-aft symmetric. The bow is the finer end: tip half-beam 0.30 units against 0.94 at the stern. Reads at ~17 m long.
   *
   * Solved on Y at 10 m, which puts it at 17.01 m long, 5.33 m wide, 10 m tall.
   * 1750 tris · 150.4 kB · source box 4.76 × 8.934 × 15.2 units.
   * Faces +Z, declared and verified by eye plus a station profile — the taper heuristic reads -z on this model and is wrong.
   */
  ferry: {
    id: 'ferry',
    file: 'ferry.glb',
    mode: 'ferry',
    role: 'vehicle',
    scale: 1.119344,
    yOffset: 0,
    yaw: 0,
    readsAtM: 10,
    readsAtAxis: 'y',
    sizeM: [5.33, 10, 17.01],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/watercraft-kit',
  },
  /**
   * Double-deck set, nose — the cab end is both lower and narrower. The sleeper read; #4 judged the kit's own carriages freight-bodied.
   *
   * Solved on Y at 4.6 m, which puts it at 5.98 m long, 3.07 m wide, 4.6 m tall.
   * 1445 tris · 142.3 kB · source box 1.285 × 1.924 × 2.5 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  train_sleeper_nose: {
    id: 'train-sleeper-nose',
    file: 'train-sleeper-nose.glb',
    mode: 'train',
    role: 'vehicle',
    scale: 2.390823,
    yOffset: 0,
    yaw: 0,
    readsAtM: 4.6,
    readsAtAxis: 'y',
    sizeM: [3.07, 4.6, 5.98],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/train-kit',
  },
  /**
   * Middle segment, fore-aft symmetric: yaw is arbitrary and set to 0 for consistency.
   *
   * Solved on Y at 4.6 m, which puts it at 6.31 m long, 3.07 m wide, 4.6 m tall.
   * 1462 tris · 142.4 kB · source box 1.285 × 1.924 × 2.638 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  train_sleeper_middle: {
    id: 'train-sleeper-middle',
    file: 'train-sleeper-middle.glb',
    mode: 'train',
    role: 'vehicle',
    scale: 2.390823,
    yOffset: 0,
    yaw: 0,
    readsAtM: 4.6,
    readsAtAxis: 'y',
    sizeM: [3.07, 4.6, 6.31],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/train-kit',
  },
  /**
   * Tail segment.
   *
   * Solved on Y at 4.6 m, which puts it at 6.31 m long, 3.07 m wide, 4.6 m tall.
   * 1262 tris · 125.4 kB · source box 1.285 × 1.924 × 2.638 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  train_sleeper_tail: {
    id: 'train-sleeper-tail',
    file: 'train-sleeper-tail.glb',
    mode: 'train',
    role: 'vehicle',
    scale: 2.390823,
    yOffset: 0,
    yaw: 0,
    readsAtM: 4.6,
    readsAtAxis: 'y',
    sizeM: [3.07, 4.6, 6.31],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/train-kit',
  },
  /**
   * High-speed set, nose — tapers from 0.65 to 0.24 half-beam at the +z tip. The daytime intercity read.
   *
   * Solved on Y at 4 m, which puts it at 6.84 m long, 3.22 m wide, 4 m tall.
   * 1261 tris · 123.1 kB · source box 1.32 × 1.637 × 2.799 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  train_intercity_nose: {
    id: 'train-intercity-nose',
    file: 'train-intercity-nose.glb',
    mode: 'train',
    role: 'vehicle',
    scale: 2.442866,
    yOffset: 0,
    yaw: 0,
    readsAtM: 4,
    readsAtAxis: 'y',
    sizeM: [3.22, 4, 6.84],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/train-kit',
  },
  /**
   * Middle segment, fore-aft symmetric.
   *
   * Solved on Y at 4 m, which puts it at 6.35 m long, 3.18 m wide, 4 m tall.
   * 1394 tris · 134.1 kB · source box 1.3 × 1.637 × 2.6 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  train_intercity_middle: {
    id: 'train-intercity-middle',
    file: 'train-intercity-middle.glb',
    mode: 'train',
    role: 'vehicle',
    scale: 2.442866,
    yOffset: 0,
    yaw: 0,
    readsAtM: 4,
    readsAtAxis: 'y',
    sizeM: [3.18, 4, 6.35],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/train-kit',
  },
  /**
   * Tail segment.
   *
   * Solved on Y at 4 m, which puts it at 6.35 m long, 3.18 m wide, 4 m tall.
   * 1138 tris · 112.7 kB · source box 1.3 × 1.637 × 2.6 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  train_intercity_tail: {
    id: 'train-intercity-tail',
    file: 'train-intercity-tail.glb',
    mode: 'train',
    role: 'vehicle',
    scale: 2.442866,
    yOffset: 0,
    yaw: 0,
    readsAtM: 4,
    readsAtAxis: 'y',
    sizeM: [3.18, 4, 6.35],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/train-kit',
  },
  /**
   * No CC0 bus exists anywhere #4 checked, and a van is the truer depiction of a minibus hop regardless. The bonnet is the +z end: body height falls from 1.35 to 0.72 units. Reads at ~5.3 m long.
   *
   * Solved on Y at 2.6 m, which puts it at 5.3 m long, 2.89 m wide, 2.6 m tall.
   * 2082 tris · 181.3 kB · source box 1.5 × 1.35 × 2.75 units.
   * Faces +Z, confirmed by Kenney's own node names.
   */
  van: {
    id: 'van',
    file: 'van.glb',
    mode: 'bus',
    role: 'vehicle',
    scale: 1.925926,
    yOffset: 0,
    yaw: 0,
    readsAtM: 2.6,
    readsAtAxis: 'y',
    sizeM: [2.89, 2.6, 5.3],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/car-kit',
  },
  /**
   * Cream two-block guesthouse with pitched gable roofs, 374 tris — #4 described the kit as flat-roofed cubes, which is true of its modular pieces but not of this pre-assembled sample. Scaled by height because it stands rather than travels, so 8 m is the RIDGE: eaves land at 6.1 m and the footprint at ~4.4 × 8.9 m.
   *
   * Solved on Y at 8 m, which puts it at 8.88 m long, 4.41 m wide, 8 m tall.
   * 374 tris · 40.0 kB · source box 1.091 × 1.981 × 2.2 units.
   */
  stay_guesthouse: {
    id: 'stay-guesthouse',
    file: 'stay-guesthouse.glb',
    role: 'stay',
    scale: 4.037855,
    yOffset: 0,
    yaw: 0,
    readsAtM: 8,
    readsAtAxis: 'y',
    sizeM: [4.41, 8, 8.88],
    licence: 'CC0-1.0',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/modular-buildings',
  },
  /**
   * Untextured, which is an advantage: Onward owns its colour. Solved on wingspan — the fuselage is the SHORTER horizontal axis on this model, and its fin is proportionally tall, so neither length nor height is a safe reference. Reads at 60 m span, ~46.5 m long.
   *
   * Solved on X at 60 m, which puts it at 46.54 m long, 60 m wide, 21.48 m tall.
   * 696 tris · 49.8 kB · source box 20.63 × 7.387 × 16.001 units.
   */
  airliner: {
    id: 'airliner',
    file: 'airliner.glb',
    mode: 'flight',
    role: 'vehicle',
    scale: 2.908398,
    yOffset: 7.0851,
    yaw: 0,
    readsAtM: 60,
    readsAtAxis: 'x',
    sizeM: [60, 21.48, 46.54],
    licence: 'CC0-1.0',
    author: 'Savino',
    source: 'https://opengameart.org/content/funky-aircraft',
  },
} as const satisfies Record<string, ModelAsset>

export type ModelAssetKey = keyof typeof MODEL_ASSETS

export const modelAssets = (): ModelAsset[] => Object.values(MODEL_ASSETS)
